### ISSUE TITLE
RoboScape not working

### ISSUE THREAD

**Issue by ColtonAnder** [NetsBlox/extensions#14]
I can open and interact with the 3D environment, however, the network blocks do not recognize any robots as valid. I have tried many methods to get it to work and nothing is. If I missed something in the documentation or network blocks please let me know.

**Comment by gsteinLTU** [comment]
Can you please tell me more about how you were trying to use the robots?

**Comment by ColtonAnder** [comment]
Im very sorry, I didn't understand the syntax for communicating. I have since figured it out. Thanks!

**Comment by gsteinLTU** [comment]
Glad you got it working, let me know if you run into any other issues!
