### ISSUE TITLE
Open in editor/dev option 

### ISSUE THREAD

**Issue by gsteinLTU** [NetsBlox/extensions#4]
For each extension, it would be nice to be able to select which instance to open it on. Each extension could specify the versions it is compatible with (most likely to be only dev, but RoboScape may end up only editor), and the link with automatically generate to editor with an option to open on dev if applicable.

**Comment by gsteinLTU** [comment]
Partially implemented in 8750a86b93b9cfdec5358f5e382b488fb5a2f953, which allows extensions to specify if they should run on dev or editor, but not links to both or any modal about dev.

**Comment by brollb** [comment]
Nice work. I actually like this approach more than a modal. Ideally, all of the extensions would use editor.netsblox.org by default (at least when thinking about usage by regular users).

That said, it might not be bad to have a hidden option to open them on dev.netsblox.org to make sure they are still compatible with the upcoming release.
